NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmarks/mnasnet_b1_1_3_cifar100_224_e100_sgd'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 5
  EVAL_EPOCH: 5
  RESUME: False
  USE_TENSORBOARD: True
DATASET:
  NAME: 'CIFAR100'
  DATA_DIR: './data/cifar'
TRANSFORM:
  MEAN: (0.45, 0.45, 0.45)
  STD: (0.225, 0.225, 0.225)
  TRAIN:
    RESIZE: True
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TRAIN_CROP_SIZE: 224
  TEST:
    RESIZE: True
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TEST_CROP_SIZE: 224
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  CONV:
    TYPE: 'Conv2d'
  NORM:
    TYPE: 'BatchNorm2d'
    SYNC_BN: False
    FIX_BN: False
    PARTIAL_BN: False
  ACT:
    TYPE: 'ReLU'
  COMPRESSION:
    WIDTH_MULTIPLIER: 1.3
    ROUND_NEAREST: 8
  BACKBONE:
    NAME: 'MNASNet'
    ARCH: 'mnasnet_b1'
    IN_PLANES: 3
  HEAD:
    NAME: 'GeneralHead2D'
    FEATURE_DIMS: 1280
    DROPOUT_RATE: 0.2
    NUM_CLASSES: 100
  RECOGNIZER:
    NAME: 'MNASNet'
    PRELOADED: ""
    PRETRAINED: ""
    PRETRAINED_NUM_CLASSES: 1000
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 0.0125
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 1e-5
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 40, 70 ]
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0