NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/benchmarks/repvgg_b2g4_acb_custom_cifar100_224_e100_sgd'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 5
  EVAL_EPOCH: 5
  RESUME: False
  USE_TENSORBOARD: True
DATASET:
  NAME: 'CIFAR100'
  DATA_DIR: './data/cifar'
TRANSFORM:
  MEAN: (0.45, 0.45, 0.45)
  STD: (0.225, 0.225, 0.225)
  TRAIN:
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TRAIN_CROP_SIZE: 224
  TEST:
    SHORTER_SIDE: 224
    CENTER_CROP: True
    TEST_CROP_SIZE: 224
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  CONV:
    TYPE: 'Conv2d'
    ADD_BLOCKS: ("RepVGGBlock", "ACBlock")
  ACT:
    TYPE: 'ReLU'
  BACKBONE:
    ARCH: 'repvgg_b2g4'
    IN_PLANES: 3
    BASE_PLANES: 64
    LAYER_PLANES: (64, 128, 256, 512)
    DOWN_SAMPLES: (1, 1, 1, 1)
  HEAD:
    DROPOUT: 0.
    NUM_CLASSES: 100
  RECOGNIZER:
    TYPE: 'RepVGG'
    PRELOADED: ""
    PRETRAINED: ""
    PRETRAINED_NUM_CLASSES: 1000
    ZERO_INIT_RESIDUAL: True
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 1.5625e-3
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 1e-4
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'CosineAnnearlingLR'
  IS_WARMUP: True
  GAMMA: 0.1
  COSINE_ANNEALING_LR:
    MINIMAL_LR: 1e-5
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0